services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    networks:
      - web
      - default
    volumes:
      - .:/var/www/html/
    links:
      - php
    labels:
      - traefik.http.routers.${DOCKER_PROJECT?project variable is required}.rule=Host(`${HOST?}`)
      - traefik.http.routers.${DOCKER_PROJECT?project variable is required}.entrypoints=https
      - traefik.http.routers.${DOCKER_PROJECT?project variable is required}.tls=true
      - traefik.http.routers.${DOCKER_PROJECT?project variable is required}.tls.certresolver=letsencrypt

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html/
    networks:
      - default

networks:
  web:
    external: true
