services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - .:/var/www/html/
    links:
      - php
    labels:
      - traefik.http.routers.example.rule=Host(`example.docker.system.net.nz`)
      - traefik.http.routers.example.entrypoints=https
      - traefik.http.routers.example.tls=true
      - traefik.http.routers.example.tls.certresolver=letsencrypt

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html/
