services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    networks:
      - web
      - default
    volumes:
      - .:/var/www/html/
    links:
      - php
    labels:
      - traefik.http.routers.example2.rule=Host(`example2.docker.system.net.nz`)
      - traefik.http.routers.example2.entrypoints=https
      - traefik.http.routers.example2.tls=true
      - traefik.http.routers.example2.tls.certresolver=letsencrypt

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html/
    networks:
      - default

networks:
  web:
    external: true
