services:
  nginx:
    image: nginx:latest
    networks:
      - web
    volumes:
      - ./html:/usr/share/nginx/html
    restart: always
    labels:
      - traefik.http.routers.nginx.rule=Host(`nginx.docker.system.net.nz`)
      - traefik.http.routers.nginx.entrypoints=https
      - traefik.http.routers.nginx.tls=true
      - traefik.http.routers.nginx.tls.certresolver=letsencrypt

networks:
  web:
    external: true
