services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: BigHairyDog
      MYSQL_USER: hhaadmin
      MYSQL_PASSWORD: BigHairyDog
    volumes:
      - dbdata:/var/lib/mysql
  pma:
    image: phpmyadmin/phpmyadmin
    networks:
      - web
      - default
    labels:
      - traefik.http.routers.pma.rule=Host(`pma.docker.system.net.nz`)
      - traefik.http.routers.pma.entrypoints=https
      - traefik.http.routers.pma.tls=true
      - traefik.http.routers.pma.tls.certresolver=letsencrypt
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
    restart: always
    volumes:
      - /sessions
      - ~/docker/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
      - /custom/phpmyadmin/theme/:/www/themes/theme/
volumes:
  dbdata:
networks:
  web:
    external: true
  default:
